### ISSUE TITLE
Add a new parameter to navigation menu items to open in a new window

### ISSUE THREAD

**Issue by parsiya** [parsiya/Hugo-Octopress#13]
Currently only the link to the root of the site is not opened in a new window. Everything else opens in a new window. Add support for a parameter in the config file.

Currently it works like this:
```
[[menu.main]]
	Name = "Blog"
	URL = "/"
	weight = -6
```
Add a parameter and then act accordingly in `navigation.html`.

```
[[menu.main]]
	Name = "Blog"
	URL = "/"
	weight = -6
	new_window = true
```

If `new_window` is true then open the menu item in a new window. If not set or if set to false, create a normal link.

**Comment by xen0l** [comment]
+1 on this

**Comment by parsiya** [comment]
Seems like you currently cannot add custom properties to menu items that are created via Hugo's menu functionality according to this thread on the forum: https://discuss.gohugo.io/t/how-to-add-a-title-attribute-to-menu-items/3335/5.

Unfortunately I cannot "repurpose" one of the current properties either. They are used by Hugo to create the menu structure. The properties are [here in the documentation](https://gohugo.io/extras/menus/).

**Comment by parsiya** [comment]
I have added a global parameter in the config file named "navigationNewWindow" instead. If this is set to true, then all navigation menu links (except links to root) will open in a new window. If this is not set or set to false then navigation menu items will not open in a new window.
