### ISSUE TITLE
Google search not getting the query search parameter while searching the blog.

### ISSUE THREAD

**Issue by piyushchauhan2011** [parsiya/Hugo-Octopress#16]
Google search when enabled in the navigation is taking to a new page with search parameter as site: <sitename> but doesn't append the `q` parameter to the `query` after `site:<sitenavigation>`. 

```html
{{ if isset .Site.Params "search_engine_url" }}
<form action="{{ .Site.Params.search_engine_url }}" method="get" target="_blank">
  <fieldset role="search">
  	<input class="search" type="text" name="q" results="0" placeholder="Search"/>
    <input type="hidden" name="q" value="site:{{ "/" | absURL }}" />
  </fieldset>
</form>
{{end}}
```

Might need to re-visit code ?

**Comment by piyushchauhan2011** [comment]
@parsiya ??

**Comment by parsiya** [comment]
Hey
Thanks for reporting this. I am currently working on-site far from home. I will take a look at it when I return.

**Comment by parsiya** [comment]
I just went through this, this is working as intended on my website. Have you changed the value of `search_engine_url` in your config file? If so, what is it and can you tell me what the search query looks like when you do a search in your blog?

**Comment by piyushchauhan2011** [comment]
Hey @parsiya , I tried search on your github website with keyword `windows` and expected to search result in google. But instead it did a general search for your website like this:
![screen shot 2016-06-26 at 3 49 24 pm](https://cloud.githubusercontent.com/assets/693487/16360759/c00c698c-3bb5-11e6-9207-a33fffdd6b17.png)

![screen shot 2016-06-26 at 3 49 11 pm](https://cloud.githubusercontent.com/assets/693487/16360760/c28d64fe-3bb5-11e6-8858-bff673b4780f.png)

I'm looking for something like this which as per the article I think can work. Let me know your thoughts about it. [Google Custom Search](http://digitaldrummerj.me/blogging-on-github-part-7-adding-a-custom-google-search/)

**Comment by parsiya** [comment]
This is strange, because I just tried it with both Firefox and Chrome and got the correct search results.

Firefox:
![Firefox](https://cloud.githubusercontent.com/assets/3981231/16366103/d3c5c85e-3bdf-11e6-8d86-f3eb5df611c8.PNG)

Chrome:
![chrome](https://cloud.githubusercontent.com/assets/3981231/16366111/df4568f6-3bdf-11e6-86bd-d89580dc6c18.PNG)

**Comment by parsiya** [comment]
Is this still an issue?

**Comment by piyushchauhan2011** [comment]
Cool 👍 @parsiya Working perfectly. Not sure what changed here but it works now. Cheers!
