### ISSUE TITLE
disqusShortname in the config file: sample-config.toml

### ISSUE THREAD

**Issue by dirk2011** [parsiya/Hugo-Octopress#24]
```
	# Disqus shortcode
	# Disable comments for a specific post by adding "comments: false" in its frontmatter
	disqusShortname = "Your Google Analytics tracking code"
```
A small mistake in the example config file, the var: `disqusShortname` sample is not correct I think.

**Comment by parsiya** [comment]
You are right. I was looking at the sentence for a few minutes trying to find out what is wrong.
