### ISSUE TITLE
Error range sidebar.html

### ISSUE THREAD

**Issue by jniltinho** [parsiya/Hugo-Octopress#3]
```html

<section class="even">
    <h1>Recent Posts</h1>

    <!-- check if the number of recent posts is set in config file, otherwise use 5 -->
    <ul id="recent_posts">
      {{ $numberofrecentposts := 5 }}
      {{ if isset .Site.Params "SidebarRecentLimit" }}
        {{ $numberofrecentpost := .Site.Params.SidebarRecentLimit }}
      {{ end }}
      {{range first $numberofrecentposts .Site.Pages }}
      <li class="post">
        <a href="{{.RelPermalink}}">{{.Title}}</a>
      </li>
      {{ end }}
    </ul>
  </section>
```

No change SidebarRecentLimit, please add  {{$numberofrecentposts}} on li for tests

```html

<section class="even">
    <h1>Recent Posts</h1>

    <!-- check if the number of recent posts is set in config file, otherwise use 5 -->
    <ul id="recent_posts">
      {{ $numberofrecentposts := 5 }}
      {{ if isset .Site.Params "SidebarRecentLimit" }}
        {{ $numberofrecentpost := .Site.Params.SidebarRecentLimit }}
      {{ end }}
      {{range first $numberofrecentposts .Site.Pages }}
      <li class="post">
        {{$numberofrecentposts}}
        <a href="{{.RelPermalink}}">{{.Title}}</a>
      </li>
      {{ end }}
    </ul>
  </section>
```

**Comment by jniltinho** [comment]
![Screen_00](https://cloud.githubusercontent.com/assets/1027494/13382850/213807b8-de5d-11e5-8113-d1bfc5dd4794.png)

![Screen_01](https://cloud.githubusercontent.com/assets/1027494/13382852/27023286-de5d-11e5-92bb-375345ff93fc.png)

**Comment by jniltinho** [comment]
In my new Blog I will use your theme and Hugo.
https://github.com/jniltinho/newblog

Thank's

**Comment by parsiya** [comment]
Thanks for using it. I am a bit confused about this issue.

Do you want me to add the `{{$numberofrecentposts}}` to the actual link text in the sidebar like your example and modification?

Or do you mean adding a number in the links in recent posts? similar to:

    1. link_1
    2. link_2

**Comment by jniltinho** [comment]
File: config.toml

```
[params]

        # number of recent posts that will be shown in the sidebar - default is 5
        SidebarRecentLimit = 10
```

The setting does not work.

**Comment by parsiya** [comment]
Ah you are right, I have forgotten to actually apply the limit from the config file. I will fix it and do a commit when I get home tonight.

Thanks for letting me know

**Comment by jniltinho** [comment]
Thank's, @parsiya 
Its design is wonderful.
Great !!!

**Comment by parsiya** [comment]
I messed up with the commit message, sorry about that :D

**Comment by parsiya** [comment]
This should fix the issue. Please let me know if it does not.

**Comment by jniltinho** [comment]
Hi @parsiya , Now it's working.

![linuxpro_blog](https://cloud.githubusercontent.com/assets/1027494/13466508/fdd14aaa-e078-11e5-923a-d5fac0708ace.png)

Congratulations for your wonderful work.

I would like to ask a question.
You have time to migrate this theme for Hugo, I can help.
http://blog.zhangruipeng.me/hexo-theme-hueman/
https://github.com/ppoffice/hexo-theme-hueman

Thank's
