### ISSUE TITLE
disqus not included

### ISSUE THREAD

**Issue by simonszu** [parsiya/Hugo-Octopress#32]
I have noticed that, although "disqusShortname" was defined, the disqus code isn't included at the bottom of each post. There is a "Comments" link at the top of the post, which links to an anchor which is undefined. 
How comes?

**Comment by parsiya** [comment]
The reason is most likely my variable name. Hugo's internal template also uses `disqusShortname` in the config file. Changing the variable solved the issue. Will make a commit soon.

**Comment by parsiya** [comment]
This should fix the issue. Let me know if it does not. Note that `disqusShortname` is not under `params` anymore in the config file. Look at the readme under `Disqus` or sample-config to see an example.
