### ISSUE TITLE
Unable to find archetypes directory

### ISSUE THREAD

**Issue by simonszu** [parsiya/Hugo-Octopress#33]
When creating a new post with `hugo new`, hugo spawns an error when using this theme:
```
ERROR 2017/05/17 10:23:44 Unable to find archetypes directory for theme "hugo-octopress" at "/home/simonszu/blog/themes/hugo-octopress/archetypes"
```

Although, the post file is created. However, this error is ugly.

**Comment by parsiya** [comment]
Does your website have an `archetypes` directory? I do not see the error in my own setup because I have one.

Alternatively I can add a default archetype to the theme. Some themes have a default one and some don't.

**Comment by simonszu** [comment]
Yes, my website has an archetype directory. I think it will be enough if you add an empty directory, since hugo does not really check the contents (which is the reason the post file is still created for now)

**Comment by mikewillems** [comment]
Hi, so this error doesn't appear at all solved. I experienced the same thing, and as the OP says, Hugo creates the post, but my repo already contains an archetypes/ directory with a default.md in it, and the error still shows up. Judging by the fact that the error message is plainly wrong (claims it's unable to find an archetypes directory at the location of an archetypes directory), I'd say this should be considered a genuine bug.

**Comment by parsiya** [comment]
OK I need to look into this in a few weeks. Currently travelling.

**Comment by mikewillems** [comment]
Thanks! Yea, no rush certainly. Safe travels!

**Comment by parsiya** [comment]
Thanks for waiting. I just created a new site. Tried with and without `default.md` in the site (kept the archetype in theme) and did not get any errors.

Can you deploy a barebones example site with the error to Github so I can figure out why you are getting the error?

**Comment by parsiya** [comment]
Closing this. Please re-open if the problem happens again.
