### ISSUE TITLE
Mastodon sidebar support.

### ISSUE THREAD

**Issue by AvnSgt** [parsiya/Hugo-Octopress#40]
Incorporate Mastodon into the Sidebar params, with icon support.

**Comment by parsiya** [comment]
Here I am thinking why someone would want the band.

Can you please give an example of a profile URL? I cannot find one. Something like `https://mastodon.social/username/`?

icon:
I found this path in the repo which does not exist anymore, https://github.com/tootsuite/mastodon/raw/master/app/assets/images/logo.png.

The original logo is here: https://assets.mastodon.social/packs/logo-1c01b10e55cd17e27a4df85991e030d9.png but it looks like that will change. We need a static URI that does not change.

**Comment by AvnSgt** [comment]
The best example I will use for this particular situation is a user I know who works in the FOSS field. Profile found here.  https://mastodon.rocks/@bryanlunduke

But, you could sub @avnsgt to view my profile. Because Mastodon is decentralized the optimal formatting would be something to the effect of, "https://mastodon.xxx/@username/" 
As for the logo changing, there is an extensive discussion here, https://github.com/tootsuite/mastodon/issues/962, but this is non-binding to my knowledge. The logo you linked is the favicon for Mastodon, and traditional logo that ships with the server.
But, I am not the best person for this, Gargron is the dev on the project. I am just one of the many users. :smiley:

**Comment by parsiya** [comment]
Ok, thanks for the information. What I want to know is how to construct the URL, if it's just like `https://mastodon.rocks/@{username}` I can just replace that from the config file. If we need to both change the tld and the username I would have to ask people to put everything after `https://mastodon.` into the config file.

With regards to logo, I just want a static URL that I need to load that does not change. So I can just load that and make it work.

**Comment by AvnSgt** [comment]
So, yeah, the you have the basic url right. I will try to contact Gargron for information on a static link to the logo. Might take a day or two. :smiley_cat:

**Comment by parsiya** [comment]
Great, thanks. Let me know if you have any preference because you are going to be one of the first people to use it (most likely). I will have a go at it over the weekend.

**Comment by AvnSgt** [comment]
I certainly hope to be using it. I am in the middle of test several Hugo Themes, one of which I plan to deploy in the near future. I really liked Octopress, when I got my hands on it, but from a social media stand point, I only use Mastodon. So, the logo would be a nice feature to have. :+1:

**Comment by parsiya** [comment]
Check the [mastodon-support](https://github.com/parsiya/Hugo-Octopress/tree/mastodon-support) branch.

It's not gonna be as good as the rest of the icons because Font Awesome icons are just fonts while this is a png. Supposedly we can convert the svg logo into a font but I do not know enough about webdev to do it. For example the highlighting and color will not be the same.

![icon1](https://user-images.githubusercontent.com/3981231/28242870-91f2a03a-6985-11e7-8f36-df39e34423c6.PNG)

**Comment by AvnSgt** [comment]
It is a start, and that's a plus. Will try to address this through the tootsuite/mastodon repo.  :+1:

**Comment by AvnSgt** [comment]
Sorry for the delay. I got caught up in a new project I started, and it is a big one. While, I had my attention taken away, Mastodon did drop a new logo change. It can be found in the same place as the old one. https://raw.githubusercontent.com/tootsuite/mastodon/master/public/favicon.ico I think the issue can be closed, if you agree. Side note: Octopress is most likely gonna be my choice, to be the front end for my project. I like it aestheticly, but I have a lot of work ahead of myself first.

**Comment by robbkidd** [comment]
*bump*

Good news! [Font Awesome has a Mastodon logo](https://fontawesome.com/v5/icons/mastodon?s=solid&f=brands) now.

I added a `mastodon` entry to `Site.Params` in `config.toml` and the following added to the sidebar template in my clone of the theme. It's basically the example from the [mastodon-support](https://github.com/parsiya/Hugo-Octopress/tree/mastodon-support) branch, but with the Font Awesome logo and a `rel="me"` attribute added to the link for [verification](https://docs.joinmastodon.org/user/profile/#verification).

```
{{ with .Site.Params.mastodon }}<a target="_blank" href="{{ . }}" title="{{ . }}" rel="me"><i class="fa fa-mastodon fa-3x"></i></a>{{ end }}
```

<img width="231" alt="Screenshot 2022-11-10 at 12 42 56 AM" src="https://user-images.githubusercontent.com/517302/201010060-6ad25858-5f97-47f1-913f-865f6cf2da17.png">
