### ISSUE TITLE
The menu.main  does not appear on the phone's browser(android chrome firefox)

### ISSUE THREAD

**Issue by xixitalk** [parsiya/Hugo-Octopress#44]
The menu.main  does not appear on the phone's browser(android chrome firefox)

**Comment by parsiya** [comment]
Yes it does not. Most likely something in my trainwreck of a CSS :D Thanks for letting me know.

**Comment by parsiya** [comment]
I went back and looked at how Octopress does it. It's with a navigation menu and I implemented the same thing in the CSS. This was too easy to be true but take a look and let me know if it's broken in another way (or broke some other thing).

This branch has the fix: https://github.com/parsiya/Hugo-Octopress/tree/mobile-nav

I will see need to see how it actually looks on mobile devices before merging.

![image](https://user-images.githubusercontent.com/3981231/33302937-b3715320-d3cd-11e7-911d-d361b61056da.png)

**Comment by parsiya** [comment]
Ok I spoke too soon, the navigation does not happen yet. I need to see what I did wrong.

**Comment by parsiya** [comment]
Navigation works now but needs JavaScript. Until I figure out how to non-JS version.

**Comment by xixitalk** [comment]
It works. thanks for the excellent work.

**Comment by parsiya** [comment]
No worries, again thanks for pointing it out. Will hopefully do a non-JS version someday.
