### ISSUE TITLE
Recent Posts lists tags and website title

### ISSUE THREAD

**Issue by nllspc** [parsiya/Hugo-Octopress#49]
This won't be a problem once I generate more posts. Plus in the meantime I can set the recent-post-limit in the config to a lower number so it only displays my actual posts but it's something that doesn't seem right so I thought I'd go ahead and create an issue. For some reason, the  index.html files getting generated in the public folder have (under id="recent_posts") categories, tags, and the title of my blog have <li class="post". I've tried to figured where and how this is created but have had no luck.

**Comment by parsiya** [comment]
They do, you are right. I never noticed because I migrated a full blog to Hugo.

Thanks for letting me know and let me take a look at it.

**Comment by nllspc** [comment]
Thanks for all the help. Everything is working great!
