### ISSUE TITLE
Compatibility with GDPR

### ISSUE THREAD

**Issue by simonszu** [parsiya/Hugo-Octopress#53]
In the European Union we get a new law, known as the GDPR, next month. It regulates all data protection issues for online media, especially including tracking stuff and polling external APIs without the user's consent. This affects fetching fonts and CSS from external servers as well. 

Currently this theme queries fonts.googleapis.com for fetching some fonts, and also the Bootstrap CDN for fetching fontawesome.css. This violates the GDPR. 

To make this theme GDPR compliant, i am asking you to modify this theme so that these fonts and CSS files are available locally, so all queries a reader's browser makes are only going to my server where hugo is hosted, and not elsewhere. I think it's not much work, but it allows european bloggers to continue using this theme. 

Yes, i know how stupid this may sound to you, and the computer guys (TM) in europe know this as well, but data protection is a big issue in europe, and the law has passed and has to be implemented until May 25th 2018, or site administrators have to face fees up to 2 million euros.

**Comment by Erethon** [comment]
There is already a setting called `disableGoogleFonts` that I added in the past for privacy reasons. I guess you can use that for GDPR compliance.

**Comment by simonszu** [comment]
Thanks, i'll check it. I hope this results in this theme not having any fonts at all. ;)
However, there is still the reference to fontAwesome...

**Comment by parsiya** [comment]
Checkout these two branches for local icons for now:

- One is fontawesome 5 which I do not like especially because the key icon for keybase is ugly: https://github.com/parsiya/Hugo-Octopress/tree/fontawesome-5
- Forkawesome is a fork of font awesome 4 and I like the icons mainly because it has the original keybase icon: https://github.com/parsiya/Hugo-Octopress/tree/forkawesome

I can add options for localizing but then the theme has to ship with those local files no matter what option is chosen, I can create a new branch but then we have to maintain two branches. Let me see what I can do, the Google fonts can be localized without a lot of extra space but I need to check the licensing. Also I need to figure out and remove one of the fonts and just use one.

**Comment by parsiya** [comment]
This commit should use local Google fonts: https://github.com/parsiya/Hugo-Octopress/commit/024f56c4c4d2c89d39eaa9d28134854d505c5abe

If it's not set, local fonts are used. You can use remote fonts by setting `remoteFonts = true` in `Params`.

The second commit adds local [ForkAwesome ](https://github.com/ForkAwesome/Fork-Awesome)local fonts: 8338c20bc222e0feb5f1ce8c7a090f36438b9969

ForkAwesome is pretty much the same as FontAwesome with the added benefit of having a free keybase icon to use in the sidebar.

With these two, the theme should be CDN free.

RE GDPR.
I work in security consulting and we have clients and offices [all over the world](https://www.synopsys.com/company/contact-synopsys/office-locations.html). Our security policy people have gotten questions about GDRP. The theme does not collect or store anything, neither do I. Whether the remote entities collect data and how is out of my control. FWIW Google says they are GDPR compliant.

**Comment by simonszu** [comment]
I really appreciate your work and your theme. I am aware that neither the theme or you collect or store anything. The problem is, according to several websites with more legislative knowledge, that the inclusion of resources out of a CDN makes the user's browser connect to other servers than he explicitly visited without his consent. 

There is a proverb here in germany, that says that no meal is eaten at the same temperature as it has been cooked. Maybe the inclusion of Google webfonts isn't as bad as everyone fears at the moment, and maybe there will come some court rulings that say it's no problem. But for now, i'd like to be on the safer side, at least until someone says else.

**Comment by simonszu** [comment]
I have tested both commits, it works great. Thank you very much.
