### ISSUE TITLE
Mixed Content in the Hugo-Octopress demo on the Hugo website

### ISSUE THREAD

**Issue by onedrawingperday** [parsiya/Hugo-Octopress#56]
Hello @parsiya   I am one of the maintainers of the Hugo Themes repository.

Recently I [reviewed](https://github.com/gohugoio/hugoThemes/issues/532) the deploy log of the Hugo Themes website and apparently [line 4](https://github.com/parsiya/Hugo-Octopress/blob/e62b793c61e75bae591e19af343f15941b955f1d/layouts/partials/header.html#L4) of your theme's header partial causes a  [Mixed Content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) browser warning on the Hugo website because it references an insecure URL. The Hugo website is served under `HTTPS`.

To fix this warning please change [line 4](https://github.com/parsiya/Hugo-Octopress/blob/e62b793c61e75bae591e19af343f15941b955f1d/layouts/partials/header.html#L4) of the header partial to `<link href="https://gmpg.org/xfn/11" rel="profile">`

Once you do the above please let me know.

Thanks

**Comment by parsiya** [comment]
Thanks a lot for catching it. Let me figure out if it even needs to be included, it was probably just added verbatim when the theme was ported from Octopress.
