### ISSUE TITLE
Warning with Hugo v0.57.2

### ISSUE THREAD

**Issue by k4rtik** [parsiya/Hugo-Octopress#59]
I am getting the following warning:

```
Module "Hugo-Octopress" is not compatible with this Hugo version; run "hugo mod graph" for more information.
```

Further, the index page is not listing any of my posts. Unsure if the two issues are related, some help will be appreciated.

FYI, I did not update since _de3a76b on Nov 13, 2016_, but now trying to rebuild using master.

**Comment by parsiya** [comment]
Sorry for not seeing this sooner, I am not sure why I did not get a notification for this.

So in Hugo v0.57.0, something has changed about `home.Pages` which has broken many themes. You can see the issue at https://github.com/gohugoio/hugoThemes/issues/682.

The latest commit has fixed the issue. Please let me know if it works or not and I will see what has gone wrong.

**Comment by k4rtik** [comment]
I found the issue, I had to add the following to my config.toml:
```
    mainSections = ["post"]
```

Your recent change at https://github.com/parsiya/Hugo-Octopress/commit/3f80dea2998fc23e531a9d9e79f95e974db9195f#diff-e8212813d07f0cfc99ce66dbd8933479R6 doesn't default to showing content as said in the README for older config files, AFAICT.

**Comment by k4rtik** [comment]
Even though my main issue is resolved, I should mention, I am still seeing the warning I posted in OP.

**Comment by parsiya** [comment]
Thanks for checking. The warning is probably because I have messed up the `min_version` in `theme.toml`. It's currently set to `min_version = 0.572` which is probably wrong.

I do not know how Hugo numbers minor versions but I cannot go with `0.57` because it has a bug that will stop the theme.

**Comment by parsiya** [comment]
I am reopening this until I can figure it out.

**Comment by onedrawingperday** [comment]
@parsiya

Hugo uses semver versions so it should be:
    min_version = "0.57.2"

**Comment by parsiya** [comment]
Thanks @onedrawingperday. I appreciate your help.
