### ISSUE TITLE
ability to override theme's favicon

### ISSUE THREAD

**Issue by nickdesaulniers** [parsiya/Hugo-Octopress#73]
Looks like in layouts/partials/header.html we have the following hardcoded:

```html
<link href="{{ "/favicon.png" | absURL }}" rel="icon">
```
I'm guessing if that was
```html
<link href="{{ $.Site.Favicon }}" rel="icon">
```
then in my config file I could do:
```toml
favicon="/favicon.ico"
```

**Comment by parsiya** [comment]
Yeah, that makes sense. Let me get it done.

**Comment by parsiya** [comment]
This is done, you can add the parameter in `params > favicon` then copy the file to your site's static directory. Path is relative to `static`.

```toml
[params]
  favicon = "myicon.png"
```

Then copy the file to  `your-site/static/myicon.png` .
