### ISSUE TITLE
support for google analytics 4

### ISSUE THREAD

**Issue by nickdesaulniers** [parsiya/Hugo-Octopress#75]
I got some email nagware from Google about Google Analytics transitioning from UA to GA4.
https://support.google.com/analytics/answer/9744165#zippy=%2Cin-this-article

The banner there reads:

> Refer to the [Universal Analytics section](https://support.google.com/analytics#topic=10094551) if you're still using a Universal Analytics property, which will [stop processing data](https://support.google.com/analytics/answer/11583528) on July 1, 2023 (July 1, 2024 for Analytics 360 properties).

So it sounds like the traditional analytics is getting shut down.  It looks like [this code](https://github.com/parsiya/Hugo-Octopress/blob/06215b5fadb0befe2cd16220d696a8bbcf15cb06/layouts/partials/footer.html#L29-L36) should probably be updated along the lines of something like [this](https://gist.github.com/zjeaton/42246742cdaf2fb46400d04c2eba9a8a)?

Dunno if you want to move folks to a new params value or reuse the existing one?

**Comment by nickdesaulniers** [comment]
It sounds like Hugo has an "internal template" for this?
https://gohugo.io/templates/internal/

**Comment by parsiya** [comment]
Hey, sorry about the delay, let me look at what's in there. It's been a while and I have no idea why I had Google Analytics in two places (I think it had something to do with disabling it in local previews so it doesn't interfere with analytics).

**Comment by nickdesaulniers** [comment]
Hi @parsiya , any thoughts on https://github.com/parsiya/Hugo-Octopress/pull/76?

**Comment by parsiya** [comment]
Thanks for reminding me. Sorry for the delay (again). I appreciate you taking the time to fix it. I have merged the PR.

I will edit the README and the sample config to mention the change.
