### ISSUE TITLE
Terms pages

### ISSUE THREAD

**Issue by jiacai2050** [parsiya/Hugo-Octopress#78]
- https://adityatelange.github.io/hugo-PaperMod/tags/
- https://github.com/adityatelange/hugo-PaperMod/blob/master/assets/css/common/terms.css

I have port terms page from hugo-PaperMod to this theme, looks like this:

<img width="908" alt="image" src="https://user-images.githubusercontent.com/3848910/229273041-0ad8487a-050c-46a4-9622-f15769ba929f.png">

Do you like this? I can create a PR if you want.

**Comment by parsiya** [comment]
Thanks for making PR, this looks nice. However, this theme is trying to replicate the original Octopress theme, so I would like to keep the current page.

**Comment by jiacai2050** [comment]
Totally makes sense, thanks for your hard work on this theme.
